### ISSUE TITLE
Using version 1.12 in BuildConfig does not work

### ISSUE THREAD

**Issue by dtamm** [dewarim/tikaParser#11]
Hey there,

i tried upgrading my plugins to the latest version, also the tikaParser Plugin. But using the latest Version (1.12) in the BuildConfig.groovy gives me the following error:

![Image of the error](http://imageshack.com/a/img924/5714/vdJcsv.png)

**Comment by dewarim** [comment]
Hi,

I tried to publish a new version of the plugin, but grails.org is currently offline / not reachable, I keep getting a Cloudflare error.

As a workaround, you can check out the tikaParser code from this repository and then run "grails maven-install". This will install the plugin in its current version to your lokal maven cache, so other Grails applications can use it (provided your dependency resolution method uses Maven).

**Comment by dadenewyyt** [comment]
am just curious if I can do that using gradle?

thanks

**Comment by dewarim** [comment]
At the moment I do not know enough about gradle to answer this - Gradle builds are on the roadmap, as I would like to upgrade Cinnamon to Grails 3.x, which (afaict) requires Gradle as build system.

**Comment by dtamm** [comment]
@dewarim Thanks for the hint, but this may be a bit "dirty", also when developing the application with a bit more people in my office :) is grails.org online again and you may try another publish of the new plugin version?

**Comment by dewarim** [comment]
I have fixed the problem (I hope). The plugin appears to be up to date again @ grails org:

http://grails.org/plugin/tika-parser

**Comment by dtamm** [comment]
works, thanks :)
